- id: '1645607794173'
  alias: Living Room Remote Switch - Top left button 1 push
  description: Set living room temperature to 16°
  trigger:
  - platform: device
    domain: mqtt
    device_id: 69d90e30a6ac2c456c91373c6b977bf1
    type: action
    subtype: button_1_single
    discovery_id: 0x04cf8cdf3c7c00bb action_button_1_single
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 16
    target:
      area_id: living_room
  - service: climate.turn_on
    data: {}
    target:
      area_id: living_room
  mode: single
- id: '1645607832752'
  alias: Living Room Remote Switch - Top right button 1 push
  description: Set living room temperature to 19°
  trigger:
  - platform: device
    domain: mqtt
    device_id: 69d90e30a6ac2c456c91373c6b977bf1
    type: action
    subtype: button_2_single
    discovery_id: 0x04cf8cdf3c7c00bb action_button_2_single
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 19
    target:
      area_id: living_room
  - service: climate.turn_on
    data: {}
    target:
      area_id: living_room
  mode: single
- id: '1645607986268'
  alias: Living Room Remote Switch - Top right button 2 pushes
  description: Set living room temperature to 20°
  trigger:
  - platform: device
    domain: mqtt
    device_id: 69d90e30a6ac2c456c91373c6b977bf1
    type: action
    subtype: button_2_double
    discovery_id: 0x04cf8cdf3c7c00bb action_button_2_double
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 20
    target:
      area_id: living_room
  - service: climate.turn_on
    data: {}
    target:
      area_id: living_room
  mode: single
- id: '1645608061440'
  alias: Living Room Remote Switch - Top left button 2 pushes
  description: Turn off living room radiators
  trigger:
  - platform: device
    domain: mqtt
    device_id: 69d90e30a6ac2c456c91373c6b977bf1
    type: action
    subtype: button_1_double
    discovery_id: 0x04cf8cdf3c7c00bb action_button_1_double
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 15
    target:
      area_id: living_room
  - service: climate.turn_off
    data: {}
    target:
      area_id: living_room
  mode: single
- id: '1645608206937'
  alias: Living Room Remote Switch - Top right button 3 pushes
  description: Set living room temperature to 20.5°
  trigger:
  - platform: device
    domain: mqtt
    device_id: 69d90e30a6ac2c456c91373c6b977bf1
    type: action
    subtype: button_2_triple
    discovery_id: 0x04cf8cdf3c7c00bb action_button_2_triple
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 20.5
    target:
      area_id: living_room
  - service: climate.turn_on
    data: {}
    target:
      area_id: living_room
  mode: single
- id: '1645608323099'
  alias: Living Room Remote Switch - Top left button 3 pushes
  description: Turn off all radiators
  trigger:
  - platform: device
    domain: mqtt
    device_id: 69d90e30a6ac2c456c91373c6b977bf1
    type: action
    subtype: button_1_triple
    discovery_id: 0x04cf8cdf3c7c00bb action_button_1_triple
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 15
    target:
      area_id:
      - living_room
      - bedroom
      - bathroom
  - service: climate.turn_off
    data: {}
    target:
      area_id:
      - living_room
      - bedroom
      - bathroom
  mode: single
- id: '1645608485742'
  alias: Living Room Remote Switch - Bottom left button 1 push
  description: Set bathroom temperature to 16°
  trigger:
  - platform: device
    domain: mqtt
    device_id: 69d90e30a6ac2c456c91373c6b977bf1
    type: action
    subtype: button_3_single
    discovery_id: 0x04cf8cdf3c7c00bb action_button_3_single
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 16
    target:
      area_id: bathroom
  - service: climate.turn_on
    data: {}
    target:
      area_id: bathroom
  mode: single
- id: '1645608585620'
  alias: Living Room Remote Switch - Bottom right button 1 push
  description: Set bathroom temperature to 20° for 20min then set to 16°
  trigger:
  - platform: device
    domain: mqtt
    device_id: 69d90e30a6ac2c456c91373c6b977bf1
    type: action
    subtype: button_4_single
    discovery_id: 0x04cf8cdf3c7c00bb action_button_4_single
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 20
    target:
      area_id: bathroom
  - service: climate.turn_on
    data: {}
    target:
      area_id: bathroom
  - delay:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  - service: climate.set_temperature
    data:
      temperature: 16
    target:
      area_id: bathroom
  mode: restart
- id: '1645608724228'
  alias: Living Room Remote Switch - Bottom left button 2 pushes
  description: Turn off bathroom radiator
  trigger:
  - platform: device
    domain: mqtt
    device_id: 69d90e30a6ac2c456c91373c6b977bf1
    type: action
    subtype: button_3_double
    discovery_id: 0x04cf8cdf3c7c00bb action_button_3_double
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 15
    target:
      area_id: bathroom
  - service: climate.turn_off
    data: {}
    target:
      area_id: bathroom
  mode: single
- id: '1645610474319'
  alias: Living Room Temperature - Set morning temperature during week
  description: ''
  trigger:
  - platform: time
    at: 05:45:00
  - platform: homeassistant
    event: start
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    after: 05:45:00
    before: 07:15:00
  action:
  - service: climate.set_temperature
    data:
      temperature: 19
    target:
      area_id: living_room
  - service: climate.turn_on
    data: {}
    target:
      area_id: living_room
  mode: single
- id: '1645610575305'
  alias: Living Room Temperature - Set day temperature during week
  description: ''
  trigger:
  - platform: time
    at: 07:15:00
  - platform: homeassistant
    event: start
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    after: 07:15:00
    before: '17:15:00'
  action:
  - service: climate.set_temperature
    data:
      temperature: 16
    target:
      area_id: living_room
  - service: climate.turn_on
    data: {}
    target:
      area_id: living_room
  mode: single
- id: '1645610717729'
  alias: Living Room Temperature - Set night temperature
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  - platform: homeassistant
    event: start
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    after: '23:00:00'
    before: 05:44:00
  action:
  - service: climate.set_temperature
    data:
      temperature: 16
    target:
      area_id: living_room
  - service: climate.turn_on
    data: {}
    target:
      area_id: living_room
  mode: single
- id: '1645610794300'
  alias: Living Room Temperature - Set evening temperature during week
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  - platform: homeassistant
    event: start
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    after: '17:00:00'
    before: '22:00:00'
  action:
  - service: climate.set_temperature
    data:
      temperature: 19
    target:
      area_id: living_room
  - service: climate.turn_on
    data: {}
    target:
      area_id: living_room
  mode: single
- id: '1645621821215'
  alias: Bedroom Remote Switch - Left button 1 push
  description: Set bedroom temperature to 16°
  trigger:
  - platform: device
    domain: mqtt
    device_id: 8e0f004373f1386ff3a511db57bfaeb3
    type: action
    subtype: button_1_single
    discovery_id: 0x04cf8cdf3c7c9a71 action_button_1_single
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 16
    target:
      area_id: bedroom
  - service: climate.turn_on
    data: {}
    target:
      area_id: bedroom
  mode: single
- id: '1645622200651'
  alias: Bedroom Remote Switch - Right button 1 push
  description: Set bedroom temperature to 19°
  trigger:
  - platform: device
    domain: mqtt
    device_id: 8e0f004373f1386ff3a511db57bfaeb3
    type: action
    subtype: button_2_single
    discovery_id: 0x04cf8cdf3c7c9a71 action_button_2_single
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 19
    target:
      area_id: bedroom
  - service: climate.turn_on
    data: {}
    target:
      area_id: bedroom
  mode: single
- id: '1645629367875'
  alias: Bedroom Remote Switch - Right button 2 pushes
  description: Set bedroom temperature to 20°
  trigger:
  - platform: device
    domain: mqtt
    device_id: 8e0f004373f1386ff3a511db57bfaeb3
    type: action
    subtype: button_2_double
    discovery_id: 0x04cf8cdf3c7c9a71 action_button_2_double
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 20
    target:
      area_id: bedroom
  - service: climate.turn_on
    data: {}
    target:
      area_id: bedroom
  mode: single
